spring:
  application:
    name: PicpayChallenge

  datasource:
    url: jdbc:postgresql://localhost:5432/picpay_challenge
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true

  redis:
    host: localhost
    port: 6379

  cache:
    redis:
      time-to-live: 60000
      cache-null-values: false

  server:
    port: 8080